FROM node:12-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn --no-cache --production --frozen-lockfile

# Build-time variables for the frontend
ARG SENTRY_DSN
ENV SENTRY_DSN=$SENTRY_DSN

ARG SENTRY_TOKEN
ENV SENTRY_TOKEN=$SENTRY_TOKEN

ARG MATOMO_URL
ENV MATOMO_URL=$MATOMO_URL

ARG MATOMO_SITE_ID
ENV MATOMO_SITE_ID=$MATOMO_SITE_ID

ARG POSTGRES_HOST
ENV POSTGRES_HOST=$POSTGRES_HOST

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG TEST_CURRENT_DATE
ENV TEST_CURRENT_DATE=$TEST_CURRENT_DATE

ARG API_URL
ENV API_URL=$API_URL

COPY next.config.js server.js  ./
COPY src/sentry.js ./src/sentry.js
COPY .next/ ./.next

USER node

CMD ["yarn", "start"]
